### ISSUE TITLE
Symlinks in modules are unsupported.

### ISSUE THREAD

**Issue by MirthScout** [oscerd/puppet-java-module#2]
# puppet module install oscerd-java
Notice: Preparing to install into /etc/puppet/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Warning: Symlinks in modules are unsupported. Please investigate symlink oscerd-java-1.0.1/spec/fixtures/modules/java/manifests->../../../../manifests.
Notice: Installing -- do not interrupt ...
Error: No such file or directory - /etc/puppet/environments/production/modules/java/spec/fixtures/modules/java/manifests
Error: Try 'puppet help module install' for usage

This is on a RHEL 5.11 system with the following puppet rpms installed:
puppetdb-terminus-2.2.2-1.el5
puppet-server-3.7.4-1.el5
puppetdb-2.2.2-1.el5
puppet-3.7.4-1.el5

**Comment by oscerd** [comment]
Hi, 
Thanks for the issue.

I've released the 1.0.2 version of the module 
https://forge.puppetlabs.com/oscerd/java

It should solve the issue.

Thank you,
Bye.

Andrea
